In [3]:
import os.path as osp

import torch

#import torch.nn.functional as F
from torch_geometric.datasets import Planetoid
import torch_geometric.transforms as T
import numpy as np
import networkx as nx
import multiprocessing as mp

from torch_geometric.utils import to_networkx
#from torch_geometric.nn import GCNConv, ChebConv  # noqa

dataset = 'Cora'
path = osp.join(osp.dirname(osp.realpath('Cora')), '..', 'data', dataset)
dataset = Planetoid(path, dataset, transform=T.NormalizeFeatures())
data = dataset[0]

In [6]:

print(data.edge_index)
G = to_networkx(data)

tensor([[   0,    0,    0,  ..., 2707, 2707, 2707],
        [ 633, 1862, 2582,  ...,  598, 1473, 2706]])


In [9]:
print(nx.shortest_path(G, 0, 2707))

[0, 633, 1701, 24, 598, 2707]


In [26]:
node_indices = np.arange(data.num_nodes)
np.random.choice(node_indices, )

array([  46, 1206, 1696, 2399,  412])

In [31]:
def sample_anchor_nodes(data, num_anchor_nodes=32):
    """
    Returns num_anchor_nodes amount of randomly sampled anchor nodes 
    """
    node_indices = np.arange(data.num_nodes)
    sampled_anchor_nodes = np.random.choice(node_indices, num_anchor_nodes)
    return sampled_anchor_nodes

In [39]:
sample_anchor_nodes(data)

array([2161, 2423, 2143,   92, 1097,  991, 2362,  721,   25, 1220, 2200,
       2310, 1561, 1810,  128,  457, 1874, 1930,  256, 1092,  183, 1391,
       2058,  779,  968, 2188, 1199, 2288, 1201, 2034,    9,  823])